[package]
name = "yfelo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
once_cell = "1.19.0"
pest_meta = "2.7.10"
pest_vm = "2.7.10"
regex = "*"
serde = "*"
serde_json = "1.0"
