[package]
name = "yfelo_core"
version = "0.1.0"
edition = "2021"
description = "core library for Yfelo template engine"
license = "MIT"

[dependencies]
dyn_std = { version = "0.3.0", path = "../external/dyn_std" }
dyn_derive = { version = "0.3.1", path = "../external/dyn_derive" }
